### ISSUE TITLE
Change GSL dependency to nmatrix-GSL

### ISSUE THREAD

**Issue by v0dro** [SciRuby/statsample#18]
An narray dependency issue mainly arises due to statsample's dependence on GSL. Maybe if we could use the nmatrix fork this will vanish. This way nmatrix will also work without name clashes.

Is the nmatrix GSL fork stable enough for this?

**Comment by IsmailM** [comment]
+1

**Comment by v0dro** [comment]
#33 does this. The PR also ensures that statsample will work with both rb-gsl and gsl-nmatrix,

**Comment by agarie** [comment]
A problem many people raised when I updated this repository (and pushed it to rubygems) is that a GSL dependency with a minor release is unexpected. Some of the complaints involved people that were surprised by statsample's "new" dependency breaking their production environment, etc.

Let's make sure that Statsample works: a) without rb-gsl and gsl-nmatrix, b) with rb-gsl, or c) with gsl-nmatrix. We can probably setup Travis to test these cases. In this situation, you should be able to work with Daru without problems.

I would rather have C implementations of the methods we need in statsample than depending on GSL, but let's talk about it another day. ;)
