### ISSUE TITLE
Runtime and Developmental dependencies are open ended

### ISSUE THREAD

**Issue by IsmailM** [SciRuby/statsample#25]
Runtime dependencies at the very least should not be open ended. If there are any major changes in these dependencies, it will break all gems/ apps using this gems...

**Comment by agarie** [comment]
I agree. Can you provide a pull request fixing this? :P

**Comment by IsmailM** [comment]
Cool, I try to put something together tonight...

**Comment by agarie** [comment]
Fixed by #26.
