### ISSUE TITLE
Fix tests in Travis

### ISSUE THREAD

**Issue by agarie** [SciRuby/statsample#30]
Tests are broken on travis: [travis-ci.org/SciRuby/statsample](https://travis-ci.org/SciRuby/statsample). 

These tests are, apparently, caused by a bug in Distribution's `F::Ruby#p_value`. Sameer introduced failing test cases in [distribution#9](https://github.com/SciRuby/distribution/pull/9)

**Comment by v0dro** [comment]
Close this too?

**Comment by agarie** [comment]
Ooops, thanks for reminding me
