### ISSUE TITLE
rubyvis and spreadsheet dependencies are outdated

### ISSUE THREAD

**Issue by minad** [SciRuby/statsample#37]

**Comment by v0dro** [comment]
Will keep this in mind for #35

**Comment by minad** [comment]
@v0dro if you run `bundle update + bundle outdated` in sciruby/sciruby you see the outdated gems.
It would be great to have a sane list of working up-to-date gems in https://github.com/SciRuby/sciruby/blob/master/gems.yml

**Comment by minad** [comment]
it seems most of the outdated deps come from statsample

**Comment by v0dro** [comment]
Thanks for pointing that out :)

I'll do the needful ASAP.

**Comment by v0dro** [comment]
Updated in #35

**Comment by v0dro** [comment]
close this issue?
