### ISSUE TITLE
Fix dependencies before 2.0.0 release

### ISSUE THREAD

**Issue by agarie** [SciRuby/statsample#39]
We can't release a new gem version with Statsample depending on 'gsl-nmatrix' and 'nmatrix'. They must be optional dependencies, like rb-gsl was.

The solution should be straightforward: move the deps from the gemspec to the Gemfile and update the post-install message so people know that Statsample can make use of NMatrix and gsl-nmatrix. Thus, someone without NMatrix and GSL installed could do a `gem install statsample -v '0.2.0'` successfully.

This is mandatory before a new version is released.

ping @v0dro

**Comment by v0dro** [comment]
Cool will do

**Comment by v0dro** [comment]
@agarie ping!

**Comment by agarie** [comment]
Hmm, that's curious. I probably messed something on my home computer. I'll try again tonight (at work right now). If everything is OK, I'll release 2.0.0. :)

**Comment by v0dro** [comment]
Close this?
