### ISSUE TITLE
Array:mean method bug

### ISSUE THREAD

**Issue by IsmailM** [SciRuby/statsample#44]
Firstly the following seems to be a bug

```
require 'statsample'
[1, 2].mean => 1
```
This should be 1.5...

See https://github.com/SciRuby/statsample/blob/master/lib/statsample.rb#L62

i.e. That section should be 

```
def mean
  self.sum.to_f / size
end
```

**Comment by agarie** [comment]
Thanks for reporting, @IsmailM. Can you open a pull request with that fix?
