### ISSUE TITLE
Logit and Probit Regression missing

### ISSUE THREAD

**Issue by onli** [SciRuby/statsample#48]
In the Readme, logit and probit regression are mentioned. But I find them nowhere in the code, only in the form of a comment mention in https://github.com/SciRuby/statsample/blob/master/lib/statsample/regression.rb#L18. Did they get lost, or are they still around somewhere?

**Comment by v0dro** [comment]
They are in a separate gem [statsample-glm](https://github.com/SciRuby/statsample-glm/).

**Comment by onli** [comment]
Thanks, that should help. That isn't documented anywhere though, right? Are there plans to merge this, or interest in getting a proposal on how to mention that in the statsample readme? Given that the gem works for me.

**Comment by v0dro** [comment]
It's going to remain a separate gem so that GLM methods remain abstracted. Will it be possible for you send a PR with updates to the statsample README? I'd be happy to merge it.
