### ISSUE TITLE
Predict using multiple regression model

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/statsample#52]
Is there a method to predict the values for new data using a trained multiple regression model?

**Comment by lokeshh** [comment]
I'm thinking about implement this method. I think the way would be to multiply coefficient of each vector with the value of that vector. Is this sufficient @agarie ?

**Comment by v0dro** [comment]
Works. Go ahead.

**Comment by lokeshh** [comment]
Its no longer needed because of https://github.com/SciRuby/statsample/issues/53
