### ISSUE TITLE
Monkey-patched `Array#sum` method changes/breaks Ruby 2.4 method functionality

### ISSUE THREAD

**Issue by sjdemartini** [SciRuby/statsample#58]
In `lib/statsample.rb`, the core Ruby `Array` class is monkey-patched to change the behavior of the `sum` method: https://github.com/SciRuby/statsample/blob/0f283e253df9e4a9c76fa23092f88ed057399ab6/lib/statsample.rb#L57-L59

Active Support (included by Rails) already defines behavior for `#sum`, which has slightly different behavior and can accept a block for evaluation: https://github.com/rails/rails/blob/3d716b9e66e334c113c98fb3fc4bcf8a945b93a1/activesupport/lib/active_support/core_ext/enumerable.rb#L2-L27

Similarly, the Ruby core library added the `#sum` method to the Enumerable class in Ruby 2.4:
* https://ruby-doc.org/core-2.4.1/Enumerable.html
* http://blog.bigbinary.com/2016/11/02/ruby-2-4-introduces-enumerable-sum.html
* https://github.com/ruby/ruby/commit/41ef7ec381338a97d15a6b4b18acd8b426a9ce79

As such, for example, the following code works both with Active Support and/or Ruby 2.4:
```ruby
> x = ['foo', 'bar']
#=> ["foo", "bar"]
> x.sum(&:bytesize)
#=> 6
```

But fails when the `statsample` 2.0 library is included in the project's Gemfile:
```ruby
> x = ['foo', 'bar']
#=> ["foo", "bar"]
> x.sum(&:bytesize)
#=> "foobar"
```

Can this monkey-patching be removed and the `sum`ing functionality be done directly only where needed? This is preventing me from using `statsample`, unfortunately.

**Comment by NOX73** [comment]
:man_facepalming: 
+1

**Comment by v0dro** [comment]
Can you send a PR with the monkey patching removed and replace instances of `Array#sum` with an appropriate method?

**Comment by sjdemartini** [comment]
I don't have the time myself to fix this, unfortunately.

**Comment by IsmailM** [comment]
We had this issue as well - We simply patched over it again after requiring statsample - not ideal (or clean) but solved the issue for us.

Imo It would be best to avoid global monkey patch - they will have unintended side-effects and break other ruby functions and make it hard to debug when they go wrong (I had no idea it was Statsample monkey-patching when I first saw this issue)...

Any chance this could be implemented as a [Refinement](https://ruby-doc.org/core-2.3.1/doc/syntax/refinements_rdoc.html) - 

Alternatively, at the very least, put them into a separate class/module and then use inheritance to monkey-patch.

One potential implementation would be: 

```ruby 
module StatSample
  module ArrayExtensions
    def sum
      ....
    end 
  end 
end 

class Array
   include StatSample::ArrayExtensions
end
```
See https://www.justinweiss.com/articles/3-ways-to-monkey-patch-without-making-a-mess/
